remove manual screen autostart

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -67,11 +67,11 @@ bindkey "^[[B" down-line-or-beginning-search # Down
 # then automatically put us into a screen(1) session.   Only try once
 # -- if $STARTED_SCREEN is set, don't try it again, to avoid looping
 # if screen fails for some reason.
-if [ "$PS1" != "" -a "${STARTED_SCREEN:-x}" = x -a "${SSH_TTY:-x}" != x ]
-then
-  STARTED_SCREEN=1 ; export STARTED_SCREEN
-  screen -RR -S main || echo "Screen failed! continuing with normal bash startup"
-fi
+#if [ "$PS1" != "" -a "${STARTED_SCREEN:-x}" = x -a "${SSH_TTY:-x}" != x ]
+#then
+#  STARTED_SCREEN=1 ; export STARTED_SCREEN
+#  screen -RR -S main || echo "Screen failed! continuing with normal bash startup"
+#fi
 # [end of auto-screen snippet]
 
 expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
